### ISSUE TITLE
[BUG]: Place item frame.

### ISSUE THREAD

**Issue by ErythroCraft** [Brokkonaut/LWCEntityLocking#5]
Hi. 
I closed the last issue, because it is to long.

The issue is a bug created by placing and registering Item frames.

**Comment by ErythroCraft** [comment]
[22:30:13] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 5.0.16
[22:30:13] [Server thread/WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:351)
[22:30:13] [Server thread/WARN]:        at com.griefcraft.listeners.LWCEntityListener.entityCreatedByPlayer(LWCEntityListener.java:182)
[22:30:13] [Server thread/WARN]:        at com.griefcraft.listeners.LWCEntityListener.onHangingPlace(LWCEntityListener.java:91)
[22:30:13] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:30:13] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[22:30:13] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:30:13] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:30:13] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:30:13] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:30:13] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[22:30:13] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[22:30:13] [Server thread/WARN]:        at net.minecraft.world.item.ItemHanging.a(ItemHanging.java:72)
[22:30:13] [Server thread/WARN]:        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:279)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:552)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1547)
[22:30:13] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[22:30:13] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[22:30:13] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[22:30:13] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[22:30:13] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[22:30:13] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162)
[22:30:13] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051)
[22:30:13] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[22:30:13] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:30:13] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because the return value of "com.griefcraft.model.Protection.getBlock()" is null
[22:30:13] [Server thread/WARN]:        at de.robotricker.transportpipes.utils.LWCUtils.onPostRegistration(LWCUtils.java:37)
[22:30:13] [Server thread/WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:343)
[22:30:13] [Server thread/WARN]:        ... 30 more

**Comment by ErythroCraft** [comment]
Maybe better I use LWCX ??

**Comment by Brokkonaut** [comment]
I created a pull request here https://github.com/BlackBeltPanda/Transport-Pipes/pull/27 that should fix the issue.

**Comment by ErythroCraft** [comment]
ok

**Comment by ErythroCraft** [comment]
Can you do this in https://github.com/LOOHP/Bookshelf too ??

**Comment by ErythroCraft** [comment]
After installing LWC version #80 I can not open the Bookshelfs.

**Comment by Brokkonaut** [comment]
As I said this is not a LWC issue, but a compatibility issue with those other plugins. I have sent them the fixes, Bookshelfs has fixed it as far as I can see, but Transport-Pipes not yet.
